# Generated by Django 3.0.4 on 2020-07-04 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Serial',
        ),
    ]
