# Generated by Django 3.0.4 on 2020-07-04 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_delete_serial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='category',
        ),
    ]
