# Generated by Django 3.0.4 on 2020-03-31 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20200329_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='image',
            field=models.URLField(verbose_name='Изображение'),
        ),
    ]
