# Generated by Django 3.0.4 on 2020-06-09 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20200331_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='fess_in_usa',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='fess_in_world',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='tagline',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='world_premier',
        ),
        migrations.AddField(
            model_name='movie',
            name='amdb',
            field=models.FloatField(null=True, verbose_name='AMDB'),
        ),
        migrations.AddField(
            model_name='movie',
            name='data_url',
            field=models.URLField(null=True, verbose_name='Адрес для данных'),
        ),
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.CharField(max_length=60, null=True, verbose_name='Продолжительность'),
        ),
        migrations.AddField(
            model_name='movie',
            name='kinopoisk',
            field=models.FloatField(null=True, verbose_name='Кинопоиск'),
        ),
        migrations.AddField(
            model_name='movie',
            name='quality',
            field=models.CharField(max_length=60, null=True, verbose_name='Качество'),
        ),
        migrations.AddField(
            model_name='movie',
            name='translate',
            field=models.CharField(max_length=60, null=True, verbose_name='Перевод'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.CharField(max_length=50, verbose_name='Страна'),
        ),
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('quality', models.CharField(max_length=50, verbose_name='Качество')),
                ('translate', models.CharField(max_length=60, verbose_name='Перевод')),
                ('duration', models.CharField(max_length=60, verbose_name='Продолжительность')),
                ('description', models.TextField(verbose_name='Описание')),
                ('poster', models.URLField(verbose_name='Постер')),
                ('year', models.PositiveSmallIntegerField(default=2020, verbose_name='Дата выхода')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('budget', models.PositiveIntegerField(default=0, help_text='указать сумму в долларах', verbose_name='Бюджет')),
                ('kinopoisk', models.FloatField(verbose_name='Кинопоиск')),
                ('amdb', models.FloatField(verbose_name='AMDB')),
                ('url', models.SlugField(max_length=200, unique=True)),
                ('data_url', models.URLField(verbose_name='Адрес для данных')),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('actors', models.ManyToManyField(related_name='serial_actors', to='movies.Actor', verbose_name='Актеры')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.Category')),
                ('directors', models.ManyToManyField(related_name='serial_director', to='movies.Actor', verbose_name='Режисер(ы)')),
                ('genres', models.ManyToManyField(to='movies.Genre', verbose_name='Жанры')),
            ],
            options={
                'verbose_name': 'Сериял',
                'verbose_name_plural': 'Сериялы',
            },
        ),
    ]
