# Generated by Django 3.0.4 on 2020-07-19 19:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0004_movie_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='dislike',
            field=models.ManyToManyField(blank=True, related_name='dislike_movie', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movie',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like_movie', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movie',
            name='viewed',
            field=models.ManyToManyField(blank=True, related_name='viewed_movie', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movie',
            name='hidden',
            field=models.ManyToManyField(blank=True, related_name='hide_movie', to=settings.AUTH_USER_MODEL),
        ),
    ]
