# Generated by Django 3.0.4 on 2020-07-27 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20200719_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('quality', models.CharField(max_length=50, verbose_name='Качество')),
                ('translate', models.CharField(max_length=60, verbose_name='Перевод')),
                ('duration', models.CharField(max_length=60, verbose_name='Продолжительность')),
                ('description', models.TextField(verbose_name='Описание')),
                ('poster', models.URLField(verbose_name='Постер')),
                ('year', models.PositiveSmallIntegerField(default=2020, verbose_name='Дата выхода')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('world_premier', models.DateField(default=datetime.date.today, verbose_name='Премьера в мире')),
                ('kinopoisk', models.FloatField(verbose_name='Кинопоиск')),
                ('amdb', models.FloatField(verbose_name='AMDB')),
                ('url', models.SlugField(max_length=200, unique=True)),
                ('data_url', models.URLField(default='http://kinogo.by/', null=True, verbose_name='Адрес для данных')),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('actors', models.ManyToManyField(related_name='serial_actors', to='movies.Actor', verbose_name='Актеры')),
                ('directors', models.ManyToManyField(related_name='serial_director', to='movies.Actor', verbose_name='Режисер(ы)')),
                ('genres', models.ManyToManyField(to='movies.Genre', verbose_name='Жанры')),
            ],
            options={
                'verbose_name': 'Сериял',
                'verbose_name_plural': 'Сериялы',
            },
        ),
    ]
