# Generated by Django 3.0.4 on 2020-07-27 17:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0006_serial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serial',
            name='world_premier',
        ),
        migrations.AddField(
            model_name='serial',
            name='budget',
            field=models.PositiveIntegerField(default=0, help_text='указать сумму в долларах', verbose_name='Бюджет'),
        ),
        migrations.AddField(
            model_name='serial',
            name='dislike',
            field=models.ManyToManyField(blank=True, related_name='dislike_serial', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serial',
            name='hidden',
            field=models.ManyToManyField(blank=True, related_name='hide_serial', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serial',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like_serial', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serial',
            name='viewed',
            field=models.ManyToManyField(blank=True, related_name='viewed_serial', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='serial',
            name='actors',
            field=models.ManyToManyField(related_name='s_actors', to='movies.Actor', verbose_name='Актеры'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='amdb',
            field=models.CharField(max_length=30, null=True, verbose_name='AMDB'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='data_url',
            field=models.URLField(null=True, verbose_name='Адрес для данных'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='directors',
            field=models.ManyToManyField(related_name='s_directors', to='movies.Actor', verbose_name='Режисер(ы)'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='duration',
            field=models.CharField(max_length=60, null=True, verbose_name='Продолжительность'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='kinopoisk',
            field=models.CharField(max_length=30, null=True, verbose_name='Кинопоиск'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='quality',
            field=models.CharField(max_length=60, null=True, verbose_name='Качество'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='translate',
            field=models.CharField(max_length=60, null=True, verbose_name='Перевод'),
        ),
    ]
