# Generated by Django 3.0.4 on 2020-07-27 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20200727_2155'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Serial',
        ),
    ]
