# Generated by Django 3.0.4 on 2020-07-27 19:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0008_delete_serial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('quality', models.CharField(max_length=60, null=True, verbose_name='Качество')),
                ('translate', models.CharField(max_length=60, null=True, verbose_name='Перевод')),
                ('duration', models.CharField(max_length=60, null=True, verbose_name='Продолжительность')),
                ('description', models.TextField(verbose_name='Описание')),
                ('poster', models.URLField(verbose_name='Постер')),
                ('year', models.PositiveSmallIntegerField(default=2020, verbose_name='Дата выхода')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('budget', models.PositiveIntegerField(default=0, help_text='указать сумму в долларах', verbose_name='Бюджет')),
                ('kinopoisk', models.CharField(max_length=30, null=True, verbose_name='Кинопоиск')),
                ('amdb', models.CharField(max_length=30, null=True, verbose_name='AMDB')),
                ('url', models.SlugField(max_length=200, unique=True)),
                ('data_url', models.URLField(null=True, verbose_name='Адрес для данных')),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('actors', models.ManyToManyField(related_name='s_actors', to='movies.Actor', verbose_name='Актеры')),
                ('directors', models.ManyToManyField(related_name='s_directors', to='movies.Actor', verbose_name='Режисер(ы)')),
                ('dislike', models.ManyToManyField(blank=True, related_name='dislike_serial', to=settings.AUTH_USER_MODEL)),
                ('genres', models.ManyToManyField(to='movies.Genre', verbose_name='Жанры')),
                ('hidden', models.ManyToManyField(blank=True, related_name='hide_serial', to=settings.AUTH_USER_MODEL)),
                ('like', models.ManyToManyField(blank=True, related_name='like_serial', to=settings.AUTH_USER_MODEL)),
                ('viewed', models.ManyToManyField(blank=True, related_name='viewed_serial', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сериял',
                'verbose_name_plural': 'Сериялы',
            },
        ),
    ]
