# Generated by Django 3.0.4 on 2020-08-11 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_serial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serial',
            options={'verbose_name': 'Сериял', 'verbose_name_plural': 'Сериялы'},
        ),
    ]
